server:
  port: 2000

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: zuul
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/** #平台服务的请求路径
      serviceId: plat_server
  prefix: /services #请求前缀